### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'max_value'

### ISSUE THREAD

**Issue by PenghangF** [acschaefer/polex#3]
when I use python to run the ncltpoles.py in ubuntu16.04, I met thiserror
![Screenshot from 2020-02-25 16-08-35](https://user-images.githubusercontent.com/55130204/75227532-4ed80d80-57e9-11ea-8f4d-e7d2515195ac.png)
:
2012-01-08
Traceback (most recent call last):
  File "ncltpoles.py", line 516, in <module>
    save_global_map()
  File "ncltpoles.py", line 119, in save_global_map
    with progressbar.ProgressBar(max_value = len(imaps)) as bar:
TypeError: __init__() got an unexpected keyword argument 'max_value'

**Comment by snbenge** [comment]
I received the same error on WSL for Ubuntu 18.04 on the same dataset

**Comment by snbenge** [comment]
Solved by:
`pip uninstall progressbar`
`pip install progressbar2`

**Comment by Huashuijingying** [comment]
I use pycham to run the ncltpoles.py in windows,received the same error
i changed 'max_value' into 'maxvalue' to adapt to the def in  progressbar.py
It seems to be working
